/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AddFriend": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "DeleteFriend": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Dreams": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Friends": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ListFriends": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SearchUsers": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Web": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}